// <auto-generated />
using CarClubAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarClubAPI.Migrations
{
    [DbContext(typeof(CarClubContext))]
    [Migration("20200530000618_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarClubAPI.Models.PlateNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlateNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "ABC123",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Number = "DEF456",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Number = "GHI789",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Number = "JKLC098",
                            VehicleId = 4
                        });
                });

            modelBuilder.Entity("CarClubAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Toyota",
                            Model = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Nissan",
                            Model = "Micra"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Honda",
                            Model = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Suzuki",
                            Model = "Swift"
                        });
                });

            modelBuilder.Entity("CarClubAPI.Models.Vehicle", b =>
                {
                    b.HasOne("CarClubAPI.Models.PlateNumber", "PlateNumber")
                        .WithOne("Vehicle")
                        .HasForeignKey("CarClubAPI.Models.Vehicle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
